# Lab 2: numpy
Name: ghaidaa alsaadi
#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [2]:
import numpy as np

# 1. A 1-D array called zeros having 10 elements and all elements set to zero.
zeros = np.zeros(10)

# 2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.
vowels = np.array(['a', 'e', 'i', 'o', 'u'])

# 3. A 2-D array called ones having 2 rows and 5 columns, all elements set to 1, dtype as int.
ones = np.ones((2, 5), dtype=int)

# 4. A 2-D array called myarray1 using nested Python lists.
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])

# 5. A 2-D array called myarray2 using arange() with specified parameters.
myarray2 = np.arange(4, 4 * 15 + 4, 4).reshape(3, 5).astype(float)

# Display the results
print("zeros:", zeros)
print("vowels:", vowels)
print("ones:\n", ones)
print("myarray1:\n", myarray1)
print("myarray2:\n", myarray2)




zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
vowels: ['a' 'e' 'i' 'o' 'u']
ones:
 [[1 1 1 1 1]
 [1 1 1 1 1]]
myarray1:
 [[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
myarray2:
 [[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [3]:
# Find dimensions, shape, size, data type, and itemsize of the arrays
arrays = {
    'zeros': zeros,
    'vowels': vowels,
    'ones': ones,
    'myarray1': myarray1,
    'myarray2': myarray2
}

for name, array in arrays.items():
    print(f"{name}:")
    print(f"  Dimensions: {array.ndim}")
    print(f"  Shape: {array.shape}")
    print(f"  Size: {array.size}")
    print(f"  Data type: {array.dtype}")
    print(f"  Itemsize: {array.itemsize} bytes\n")

# Reshape the array ones to have all 10 elements in a single row
ones_reshaped = ones.reshape(1, -1)
print("Reshaped ones:\n", ones_reshaped)

# Display the 2nd and 3rd element of the array vowels
print("2nd and 3rd elements of vowels:", vowels[1:3])

# Display all elements in the 2nd and 3rd row of the array myarray1
print("2nd and 3rd rows of myarray1:\n", myarray1[1:3])

# Display the elements in the 1st and 2nd column of the array myarray1
print("1st and 2nd columns of myarray1:\n", myarray1[:, 0:2])

# Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1
print("1st column of the 2nd and 3rd row of myarray1:", myarray1[1:3, 0])

# Reverse the array of vowels
vowels_reversed = vowels[::-1]
print("Reversed vowels:", vowels_reversed)



zeros:
  Dimensions: 1
  Shape: (10,)
  Size: 10
  Data type: float64
  Itemsize: 8 bytes

vowels:
  Dimensions: 1
  Shape: (5,)
  Size: 5
  Data type: <U1
  Itemsize: 4 bytes

ones:
  Dimensions: 2
  Shape: (2, 5)
  Size: 10
  Data type: int32
  Itemsize: 4 bytes

myarray1:
  Dimensions: 2
  Shape: (3, 3)
  Size: 9
  Data type: float64
  Itemsize: 8 bytes

myarray2:
  Dimensions: 2
  Shape: (3, 5)
  Size: 15
  Data type: float64
  Itemsize: 8 bytes

Reshaped ones:
 [[1 1 1 1 1 1 1 1 1 1]]
2nd and 3rd elements of vowels: ['e' 'i']
2nd and 3rd rows of myarray1:
 [[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
1st and 2nd columns of myarray1:
 [[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]
1st column of the 2nd and 3rd row of myarray1: [  3.4 -19. ]
Reversed vowels: ['u' 'o' 'i' 'e' 'a']


Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [4]:
import numpy as np

# Assuming zeros, vowels, ones, myarray1, myarray2 have been defined as before

# Reshape myarray1 to be 3x5 for compatibility
myarray1 = np.array([[2.7, 0, -2, 0, 0], 
                      [3.4, 10.6, 0, 0, 0], 
                      [-19, 99.9, 13, 0, 0]])

# Divide all elements of array ones by 3
ones_divided = ones / 3
print("Array ones divided by 3:\n", ones_divided)

# Add the arrays myarray1 and myarray2
myarray_added = myarray1 + myarray2
print("Sum of myarray1 and myarray2:\n", myarray_added)

# Subtract myarray1 from myarray2 and store the result in a new array
myarray_subtracted = myarray2 - myarray1
print("myarray2 - myarray1:\n", myarray_subtracted)

# Multiply myarray1 and myarray2 elementwise
myarray_multiplied = myarray1 * myarray2
print("Elementwise multiplication of myarray1 and myarray2:\n", myarray_multiplied)

# Do the matrix multiplication of myarray1 and myarray2
myarray3 = np.dot(myarray1, myarray2.T)  # Transpose myarray2 for proper matrix multiplication
print("Matrix multiplication of myarray1 and myarray2:\n", myarray3)

# Divide myarray1 by myarray2
myarray_divided = myarray1 / myarray2
print("myarray1 divided by myarray2:\n", myarray_divided)

# Find the cube of all elements of myarray1 and divide the resulting array by 2
myarray1_cubed_divided = (myarray1 ** 3) / 2
print("Cube of myarray1 elements divided by 2:\n", myarray1_cubed_divided)

# Find the square root of all elements of myarray2 and divide the resulting array by 2
myarray2_sqrt_divided = np.sqrt(myarray2) / 2
myarray2_sqrt_divided = np.round(myarray2_sqrt_divided, 2)  # Round to two places of decimals
print("Square root of myarray2 elements divided by 2 (rounded):\n", myarray2_sqrt_divided)

Array ones divided by 3:
 [[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]]
Sum of myarray1 and myarray2:
 [[  6.7   8.   10.   16.   20. ]
 [ 27.4  38.6  32.   36.   40. ]
 [ 25.  147.9  65.   56.   60. ]]
myarray2 - myarray1:
 [[  1.3   8.   14.   16.   20. ]
 [ 20.6  17.4  32.   36.   40. ]
 [ 63.  -51.9  39.   56.   60. ]]
Elementwise multiplication of myarray1 and myarray2:
 [[  10.8    0.   -24.     0.     0. ]
 [  81.6  296.8    0.     0.     0. ]
 [-836.  4795.2  676.     0.     0. ]]
Matrix multiplication of myarray1 and myarray2:
 [[-1.3200e+01  8.0000e-01  1.4800e+01]
 [ 9.8400e+01  3.7840e+02  6.5840e+02]
 [ 8.7920e+02  2.7572e+03  4.6352e+03]]
myarray1 divided by myarray2:
 [[ 0.675       0.         -0.16666667  0.          0.        ]
 [ 0.14166667  0.37857143  0.          0.          0.        ]
 [-0.43181818  2.08125     0.25        0.          0.        ]]
Cube of myarray1 elements divided by 2:
 [[ 9.8

Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [5]:
# Find the transpose of ones and myarray2
ones_transpose = ones.T
myarray2_transpose = myarray2.T
print("Transpose of ones:\n", ones_transpose)
print("Transpose of myarray2:\n", myarray2_transpose)

# Sort the array vowels in reverse
vowels_sorted_reverse = np.sort(vowels)[::-1]
print("Vowels sorted in reverse order:", vowels_sorted_reverse)

# Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on
myarray1_sorted = np.sort(myarray1, axis=0)  # Sort along columns
print("myarray1 sorted column-wise:\n", myarray1_sorted)




Transpose of ones:
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
Transpose of myarray2:
 [[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]
Vowels sorted in reverse order: ['u' 'o' 'i' 'e' 'a']
myarray1 sorted column-wise:
 [[-19.    0.   -2.    0.    0. ]
 [  2.7  10.6   0.    0.    0. ]
 [  3.4  99.9  13.    0.    0. ]]


Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result. 

In [6]:
import numpy as np

# Create a 2-D array called myarray4 with 56 elements
myarray4 = np.arange(1, 14 + 1, 0.25)  # This creates an array with 52 elements

# Split this array into 3 equal parts
myarray4_split = np.array_split(myarray4, 3)

# Print the split parts
for i, part in enumerate(myarray4_split):
    print(f"\nPart {i + 1}:\n", part)


Part 1:
 [1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75 5.   5.25 5.5 ]

Part 2:
 [ 5.75  6.    6.25  6.5   6.75  7.    7.25  7.5   7.75  8.    8.25  8.5
  8.75  9.    9.25  9.5   9.75 10.   10.25]

Part 3:
 [10.5  10.75 11.   11.25 11.5  11.75 12.   12.25 12.5  12.75 13.   13.25
 13.5  13.75 14.   14.25 14.5  14.75]


Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

In [7]:
import numpy as np

# Create a 1-D array called myarray4
myarray4 = np.arange(1, 14 + 1, 0.25)  # This creates an array with 56 elements

# Reshape to a two-dimensional array
myarray4 = myarray4.reshape(7, 8)  # Reshape to 7 rows and 8 columns

# Print the shape to confirm
print("Shape of myarray4:", myarray4.shape)

# Find the sum of all elements
total_sum = np.sum(myarray4)
print("Sum of all elements:", total_sum)

# Find the sum of all elements row-wise
row_sum = np.sum(myarray4, axis=1)
print("Sum of all elements row-wise:", row_sum)

# Find the sum of all elements column-wise
column_sum = np.sum(myarray4, axis=0)
print("Sum of all elements column-wise:", column_sum)

# Find the max of all elements
max_value = np.max(myarray4)
print("Max of all elements:", max_value)

# Find the min of all elements in each row
min_values_row = np.min(myarray4, axis=1)
print("Min of all elements in each row:", min_values_row)

# Find the mean of all elements in each row
mean_values_row = np.mean(myarray4, axis=1)
print("Mean of all elements in each row:", mean_values_row)

# Find the standard deviation column-wise
std_dev_column = np.std(myarray4, axis=0)
print("Standard deviation column-wise:", std_dev_column)

Shape of myarray4: (7, 8)
Sum of all elements: 441.0
Sum of all elements row-wise: [ 15.  31.  47.  63.  79.  95. 111.]
Sum of all elements column-wise: [49.   50.75 52.5  54.25 56.   57.75 59.5  61.25]
Max of all elements: 14.75
Min of all elements in each row: [ 1.  3.  5.  7.  9. 11. 13.]
Mean of all elements in each row: [ 1.875  3.875  5.875  7.875  9.875 11.875 13.875]
Standard deviation column-wise: [4. 4. 4. 4. 4. 4. 4. 4.]


#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [8]:
import pandas as pd
import numpy as np

# Load the data
df = pd.read_csv("country-capital-lat-long-population.csv")

# Get the coordinates of Riyadh
riyadh_coords = df[df['Country'] == 'Saudi Arabia'][['Latitude', 'Longitude']].to_numpy()[0]

# Extract the coordinates of all capital cities
coordinates = df[['Capital City', 'Latitude', 'Longitude']].to_numpy()

# Calculate the Euclidean distance
distances = np.sqrt((coordinates[:, 1].astype(float) - riyadh_coords[0])**2 + 
                    (coordinates[:, 2].astype(float) - riyadh_coords[1])**2)

# Find the index of the closest capital city
closest_index = np.argmin(distances)

# Get the closest capital city name and its coordinates
closest_capital = coordinates[closest_index]
closest_capital_name = closest_capital[0]
closest_capital_coords = closest_capital[1:]

print(f"The closest capital city to Riyadh is {closest_capital_name} at coordinates {closest_capital_coords}.")



The closest capital city to Riyadh is Ar-Riyadh (Riyadh) at coordinates [24.6905 46.7096].


#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [9]:
import pandas as pd
import numpy as np

# Load the data
df = pd.read_csv("country-capital-lat-long-population.csv")

# Get the coordinates of Washington, D.C.
dc_coords = df[df['Capital City'] == 'Washington, D.C.'][['Latitude', 'Longitude']].to_numpy()[0]

# Extract the coordinates of all capital cities along with their countries
coordinates = df[['Country', 'Capital City', 'Latitude', 'Longitude']].to_numpy()

# Calculate the Euclidean distance to Washington, D.C.
distances = np.sqrt((coordinates[:, 2].astype(float) - dc_coords[0])**2 + 
                    (coordinates[:, 3].astype(float) - dc_coords[1])**2)

# Get the indices of the top 10 closest capital cities
top_10_indices = np.argsort(distances)[:10]

# Extract the top 10 closest capital cities and their coordinates
top_10_countries = coordinates[top_10_indices, 0]  # Country names
top_10_coordinates = coordinates[top_10_indices, 2:4]  # Coordinates (Latitude, Longitude)

# Print the names of the countries
print("Top 10 capital cities closest to Washington, D.C.:")
for country in top_10_countries:
    print(country)

# Print the NumPy array containing the coordinates of the top 10 cities
print("\nCoordinates of the top 10 capital cities:")
print(top_10_coordinates)



Top 10 capital cities closest to Washington, D.C.:
United States of America
Canada
Bahamas
Bermuda
Cuba
Turks and Caicos Islands
Cayman Islands
Haiti
Jamaica
Dominican Republic

Coordinates of the top 10 capital cities:
[[38.8951 -77.0364]
 [45.4166 -75.698]
 [25.0582 -77.3431]
 [32.2915 -64.778]
 [23.1195 -82.3785]
 [21.4612 -71.1419]
 [19.2866 -81.3744]
 [18.5392 -72.335]
 [17.997 -76.7936]
 [18.4896 -69.9018]]
